swiftmailer:
    transport:        gmail
    username:         '%swiftmailer_username%'
    password:         '%swiftmailer_password%'
    host:             smtp.gmail.com
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
