controllers:
    resource: '../src/Controller/'
    type:     annotation

#index:
#    path: /
#    controller: App\Controller\UserController::list

contact:
    path: /contact
    controller: App\Controller\EmailsController::contact