controllers:
    resource: '../src/Controller/'
    type:     annotation

#index:
#    path: /
#    controller: App\Controller\UserController::list

contact:
    path: /contact
    controller: App\Controller\EmailController::contact

service:
    path: /service
    controller: App\Controller\MyAdmin\AdminController::new